package ports

import (
	"context"
)

type KafkaConsumer interface {
	Consume(ctx context.Context, topics, groupId string, resultChan chan []byte) error
	Close() error
}

/*
When using the ports.KafkaProducer, there are two channels available: one for success logs and another for error logs. However, the logging context is not set externally. Instead, the NewProducer function creates a context internally using context.Background(). Consequently, the logs generated by this producer do not include  `trace_id` field, as the context lacks this information.
*/
type KafkaProducer interface {
	Produce(topic string, value []byte)
}

type KafkaMessage struct {
	Value  []byte
	Offset int64
	Topic  string
}
